/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  IMyGovernorHelper,
  IMyGovernorHelperInterface,
} from "../../../contracts/MyGovernor.sol/IMyGovernorHelper";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
      {
        internalType: "contract ICompoundTimelock",
        name: "_timelock",
        type: "address",
      },
    ],
    name: "newProject",
    outputs: [
      {
        internalType: "address",
        name: "newContract",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];

export class IMyGovernorHelper__factory {
  static readonly abi = _abi;
  static createInterface(): IMyGovernorHelperInterface {
    return new utils.Interface(_abi) as IMyGovernorHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMyGovernorHelper {
    return new Contract(address, _abi, signerOrProvider) as IMyGovernorHelper;
  }
}
