/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBoxLocal__factory } from "./IBoxLocal__factory";
export { IERC721__factory } from "./IERC721__factory";
export { IMyGovernor__factory } from "./IMyGovernor__factory";
export { IProjectNftToken__factory } from "./IProjectNftToken__factory";
export { ProjectGovernor__factory } from "./ProjectGovernor__factory";
