/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as myGovernorSol from "./MyGovernor.sol";
import type * as myGovernorHelperSol from "./MyGovernorHelper.sol";
import type * as projectGovernorSol from "./ProjectGovernor.sol";
import type * as ingoreSol from "./ingore.sol";

export type { myGovernorSol };

export type { myGovernorHelperSol };

export type { projectGovernorSol };

export type { ingoreSol };
export type { Box } from "./Box";
export type { BoxLocal } from "./BoxLocal";
export type { Greeter } from "./Greeter";
export type { IgnoreProject } from "./IgnoreProject";
export type { MyNftToken } from "./MyNftToken";
export type { ProjectNftToken } from "./ProjectNftToken";
export type { Timelock } from "./Timelock";
