/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMyGovernor__factory } from "./IMyGovernor__factory";
export { MyGovernorHelper__factory } from "./MyGovernorHelper__factory";
