/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMyGovernor } from "./IMyGovernor";
export type { MyGovernorHelper } from "./MyGovernorHelper";
