/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBoxLocal } from "./IBoxLocal";
export type { IERC721 } from "./IERC721";
export type { IMyGovernor } from "./IMyGovernor";
export type { IProjectNftToken } from "./IProjectNftToken";
export type { ProjectGovernor } from "./ProjectGovernor";
