/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  IStakeNftToken,
  IStakeNftTokenInterface,
} from "../../../contracts/ProjectCV.sol/IStakeNftToken";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "releaseFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IStakeNftToken__factory {
  static readonly abi = _abi;
  static createInterface(): IStakeNftTokenInterface {
    return new utils.Interface(_abi) as IStakeNftTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStakeNftToken {
    return new Contract(address, _abi, signerOrProvider) as IStakeNftToken;
  }
}
